#!/usr/bin/env python3
"""Export the census findings as actionable repair packets.

The audit knows exactly what the paper says for every flagged question, so the
content session should not have to re-derive any of it. Each packet pairs the
stored record with the transcription and states what to do, which keeps the fix
mechanical and auditable instead of a fresh judgement call per question.

Writes scripts/.fabrication_audit/repairs/*.json plus a readable REPAIRS.md.
"""
from __future__ import annotations

import json
from pathlib import Path

from fabrication_diff import load_stored, load_gemini, judge

ROOT = Path(__file__).resolve().parent.parent
AUDIT = ROOT / "scripts" / ".fabrication_audit"
OUT = AUDIT / "repairs"

# Proven invented: no question of this kind exists in any of the 16 papers, and its
# option set has 0% overlap with all 1041 transcribed questions.
# NOTE (2026-07-22): ENGAA-2020-PHY-014 was previously listed here. PDF hand-check
# shows it IS the real ENGAA_2020 q28 (coil/torque). Flash had shifted that slot.
FABRICATED: list[str] = []

# Same question printed in both series that year. Real content, wrong attribution.
# Resolved 2026-07-22: NSAA phantoms deleted; crane added as ENGAA-2017-PHY-027.
TWINS: dict[str, tuple[str, int]] = {}

# Census still flags these; PDF adjudication says leave alone.
KNOWN_FALSE_POSITIVES = {
    "NSAA-2016-PHY-023",
    "NSAA-2017-CHEM-017",
    "ENGAA-2018-PHY-021",
}


def packet(rec: dict, got: dict | None, action: str, note: str) -> dict:
    return {
        "id": rec.get("id"),
        "action": action,
        "note": note,
        "stored": {
            "question": rec.get("question", ""),
            "options": rec.get("options", {}),
            "answer": rec.get("answer"),
        },
        "paper_says": None if not got else {
            "qnum": got.get("qnum"),
            "question": got.get("question", ""),
            "options": {o["letter"]: o["text"] for o in got.get("options", [])},
            "diagram": got.get("diagram"),
            "transcribed_by": got.get("_model"),
        },
    }


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    # census.json includes ids recovered via proposed_mapping.json; load them the
    # same way or KeyError on every newly-mapped id.
    stored = load_stored(AUDIT / "proposed_mapping.json")
    gem = load_gemini()
    rows = json.load(open(AUDIT / "census.json", encoding="utf-8"))
    by_id = {r["id"]: r for r in rows}
    stored_by_id = {q.get("id"): (k, q) for k, q in stored.items()}

    groups: dict[str, list] = {"fabricated": [], "mapping": [], "drift": [],
                               "twin": []}

    for qid in FABRICATED:
        hit = stored_by_id.get(qid)
        if not hit:
            print(f"skip fabricated {qid}: not in stored (mapping missing?)")
            continue
        key, rec = hit
        groups["fabricated"].append(packet(
            rec, None, "DELETE or REPLACE",
            "Not present in any of the 16 papers; 0% option overlap corpus-wide. "
            "Invented. Do not try to repair it — remove it, or replace it with the "
            "real question at this number."))

    for qid, (tp, tq) in TWINS.items():
        hit = stored_by_id.get(qid)
        if not hit:
            print(f"skip twin {qid}: not in stored (mapping missing?)")
            continue
        key, rec = hit
        groups["twin"].append(packet(
            rec, gem.get((tp, tq)), "REMAP (cross-paper)",
            f"Content is genuine but belongs to {tp} q{tq}. NSAA and ENGAA shared "
            f"questions each year. Fix the attribution/mapping, not the content."))

    for r in rows:
        qid = r["id"]
        if qid in FABRICATED or qid in TWINS or qid in KNOWN_FALSE_POSITIVES:
            continue
        hit = stored_by_id.get(qid)
        if not hit:
            print(f"skip {qid}: not in stored (mapping missing?)")
            continue
        key, rec = hit
        if r["verdict"] == "MISMATCH" and r.get("found_at"):
            groups["mapping"].append(packet(
                rec, gem.get((r["paper"], r["found_at"])), "REMAP",
                f"Stored as q{r['qnum']} but the paper prints it at "
                f"q{r['found_at']}. Content is real; the id->qnum mapping is wrong."))
        elif r["verdict"] == "DRIFT":
            groups["drift"].append(packet(
                rec, gem.get((r["paper"], r["qnum"])), "REPAIR CONTENT",
                "Right question, garbled extraction. Rewrite stem/options to match "
                "`paper_says` exactly. Re-check `answer` BY VALUE afterwards — "
                "options are shuffled at render, so a stored letter means nothing."))

    for name, items in groups.items():
        (OUT / f"{name}.json").write_text(
            json.dumps(items, ensure_ascii=False, indent=2), encoding="utf-8")
        print(f"{name:12} {len(items):3} -> repairs/{name}.json")

    lines = ["# Census repairs", "",
             "Generated by `scripts/fabrication_export.py`. Every entry carries what "
             "the source paper actually says, so nothing needs re-deriving.", ""]
    titles = {
        "fabricated": "Fabricated — delete or replace",
        "twin": "Cross-paper twins — fix attribution",
        "mapping": "Mapping errors — question exists at a different number",
        "drift": "Garbled extraction — repair content against the paper",
    }
    for name in ["fabricated", "twin", "mapping", "drift"]:
        items = groups[name]
        lines += [f"## {titles[name]} ({len(items)})", ""]
        for p in items:
            tgt = p["paper_says"]
            lines.append(f"- `{p['id']}` — {p['action']}"
                         + (f" → paper q{tgt['qnum']}" if tgt else ""))
        lines.append("")
    (OUT / "REPAIRS.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"\nsummary: {OUT / 'REPAIRS.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
